name: Build and Release for Multiple Platforms and Architectures

on:
  push:
    branches:
      - release  # 仅当推送代码到 release 分支时触发

env:
  VERSION: "0.0.1-alpha"  # 全局变量：版本号

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # arch: [x64, arm64]
        os: [windows-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"



      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install ccache

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install ccache
          echo "/usr/local/opt/ccache/libexec" >> $GITHUB_PATH

      - name: Cache Visual Studio Build Tools Installer (Windows)
        if: matrix.os == 'windows-latest'
        id: cache-vs-installer
        uses: actions/cache@v3
        with:
          path: vs_buildtools.exe
          key: ${{ runner.os }}-vsinstaller-2022

      - name: Download Visual Studio Build Tools
        if: matrix.os == 'windows-latest' && steps.cache-vs-installer.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Write-Host "🌐 Downloading Visual Studio Build Tools..."
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_buildtools.exe"

      - name: Install Visual Studio Build Tools (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Write-Host "🛠️ Installing Visual Studio Build Tools..."
          Start-Process -FilePath ".\vs_buildtools.exe" -ArgumentList `
            "--quiet", `
            "--add", "Microsoft.VisualStudio.Workload.VCTools", `
            "--includeRecommended", `
            "--add", "Microsoft.VisualStudio.Component.VC.Tools.ARM64" `
            -Wait

          Remove-Item -Path ".\vs_buildtools.exe"

      - name: Configure MSVC Environment (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          :: 运行 vcvarsall.bat 以设置 MSVC 环境变量
          CALL "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }}

      # - name: Download Dependency Walker
      #   if: matrix.os == 'windows-latest'
      #   shell: cmd
      #   run: |
      #     mkdir -p "C:\Users\RUNNER~1\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\depends\x86_64"
      #     curl -L https://dependencywalker.com/depends22_x64.zip -o depends.zip
      #     tar -xf depends.zip -C "C:\Users\RUNNER~1\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\depends\x86_64"
      #     del depends.zip


      - name: Create and Activate Virtual Environment (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          python -m venv .venv
          source ./.venv/bin/activate

      - name: Create and Activate Virtual Environment (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-



      - name: Install Python dependencies in Virtual Environment (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          source ./.venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Python dependencies in Virtual Environment (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt



      - name: Build Executive in Virtual Environment (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          source ./.venv/bin/activate
          pyside6-deploy main.py -c build_config/pysidedeploy-${{ matrix.arch }}-${{ matrix.arch }}.spec --force --verbose

      - name: Build Executive in Virtual Environment (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          CALL "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }} && ^
          .\.venv\Scripts\Activate && ^
          pyside6-deploy main.py -c build_config/pysidedeploy-windows-${{ matrix.arch }}.spec --force --verbose



      - name: Upload Artifact (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos-${{ matrix.arch }}
          path: |
            ./*.app

      - name: Upload Artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux-${{ matrix.arch }}
          path: |
            ./*.bin

      - name: Upload Artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build-output-windows-${{ matrix.arch }}
          path: |
            ./*.exe


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/release')  # 仅在 release 分支上执行
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            This is a release for version ${{ env.VERSION }}.
          draft: true  # 将发布设置为草稿
          files: |
            artifacts/build-output-macos-x64/*.app
            artifacts/build-output-macos-arm64/*.app
            artifacts/build-output-linux-x64/*.bin
            artifacts/build-output-linux-arm64/*.bin
            artifacts/build-output-windows-x64/*.exe
            artifacts/build-output-windows-arm64/*.exe